# lightning.pytorch==2.0.9
seed_everything: 42
sweep: false
trainer:
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: 32-true
  fast_dev_run: false
  max_epochs: 30
  check_val_every_n_epoch: 10
  detect_anomaly: true
model:
  learning_rate: 0.0002
  views: ["FO", "DL"]
  test_views: ["FO"]
  batch_size: 6
  debug_images: false
  ortho_project: false
  pretrain_path: /zhome/0c/6/109332/Projects/MotionBERT/models/model.bin
  lambda_scale: 0.5
  lambda_3d_velocity: 20.0
  lambda_lv: 0.0
  lambda_lg: 0.0
  lambda_a: 0.0
  lambda_av: 0.0
  lambda_consistency: 0.4
  lambda_3d_pos: 1.0
data:
  data_path: /work3/ckin/bigdata/SportsPose/MarkerlessEndBachelor_withVideoPaths
  video_path: /work3/ckin/bigdata/SportsPose/videos
  views: ["FO", "DL"]
  test_views: ["FO"]
  batch_size: 6
  include_debug_images: false
#ckpt_path: /work3/ckin/motionbert_data